#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/reish/parser.y".
#

require 'racc/parser'



  require "reish/token"
  require "reish/node"


module Reish

  class Parser < Racc::Parser

module_eval <<'..end lib/reish/parser.y modeval..id9f54fae33e', 'lib/reish/parser.y', 311

  def initialize(lex)
    @yydebug = true

    @lex = lex
  end

  def next_token
    @lex.racc_token
  end
..end lib/reish/parser.y modeval..id9f54fae33e

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 2, 44, :_reduce_1,
 1, 44, :_reduce_2,
 1, 44, :_reduce_3,
 1, 45, :_reduce_none,
 2, 45, :_reduce_5,
 2, 45, :_reduce_none,
 1, 47, :_reduce_7,
 3, 47, :_reduce_8,
 3, 47, :_reduce_9,
 4, 48, :_reduce_10,
 4, 48, :_reduce_11,
 1, 48, :_reduce_none,
 1, 50, :_reduce_none,
 2, 50, :_reduce_none,
 4, 51, :_reduce_15,
 4, 51, :_reduce_16,
 1, 51, :_reduce_none,
 1, 52, :_reduce_none,
 1, 52, :_reduce_none,
 2, 52, :_reduce_none,
 2, 53, :_reduce_21,
 5, 53, :_reduce_22,
 0, 56, :_reduce_23,
 2, 56, :_reduce_24,
 1, 55, :_reduce_none,
 1, 58, :_reduce_none,
 1, 58, :_reduce_none,
 1, 58, :_reduce_none,
 1, 58, :_reduce_none,
 1, 58, :_reduce_none,
 1, 54, :_reduce_none,
 1, 54, :_reduce_none,
 1, 54, :_reduce_none,
 1, 54, :_reduce_none,
 1, 54, :_reduce_none,
 0, 65, :_reduce_36,
 0, 66, :_reduce_37,
 8, 62, :_reduce_38,
 2, 64, :_reduce_none,
 1, 64, :_reduce_none,
 6, 63, :_reduce_41,
 8, 63, :_reduce_42,
 7, 63, :_reduce_43,
 5, 68, :_reduce_44,
 7, 68, :_reduce_45,
 6, 68, :_reduce_46,
 2, 67, :_reduce_none,
 1, 67, :_reduce_none,
 3, 60, :_reduce_49,
 1, 61, :_reduce_50,
 1, 57, :_reduce_51,
 2, 57, :_reduce_52,
 4, 57, :_reduce_53,
 4, 57, :_reduce_54,
 4, 57, :_reduce_55,
 1, 69, :_reduce_56,
 4, 69, :_reduce_57,
 4, 69, :_reduce_58,
 4, 69, :_reduce_59,
 2, 59, :_reduce_60,
 2, 59, :_reduce_61,
 3, 59, :_reduce_62,
 3, 59, :_reduce_63,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 3, 59, :_reduce_none,
 3, 59, :_reduce_none,
 2, 59, :_reduce_none,
 2, 59, :_reduce_none,
 1, 46, :_reduce_none,
 1, 46, :_reduce_none,
 0, 49, :_reduce_none,
 2, 49, :_reduce_none ]

racc_reduce_n = 108

racc_shift_n = 184

racc_action_table = [
    43,   166,    46,    50,   112,   113,   114,   149,   167,   168,
    33,    34,   127,     4,   128,     9,    54,    56,    58,    60,
    61,    41,    42,    44,    45,    48,    51,    53,   146,    57,
    59,   143,   132,    84,   129,    81,   125,   155,   124,    33,
    34,    33,    34,   148,   122,   135,   145,   134,    86,   131,
    83,   156,   122,   147,    33,    34,   144,   133,    85,   130,
    82,     8,    12,   122,   121,    33,    34,    23,    33,    34,
   136,     5,   121,    11,    13,    65,    18,    33,    34,    31,
    32,    23,     4,   121,     9,     5,   137,    11,    13,    65,
    18,    36,    37,    36,    37,    23,     4,   138,     9,     5,
   139,    11,    13,    65,    18,    33,    34,   175,   140,    23,
     4,   141,     9,     5,   142,    11,    13,    65,    18,    33,
    34,    36,    37,    23,     4,   123,     9,     5,   111,    11,
    13,    65,    18,    27,    28,    33,    34,    23,     4,   126,
     9,     5,   150,    11,    13,    65,    18,    36,    37,   151,
   100,    23,     4,    89,     9,     5,    88,    11,    13,    65,
    18,    87,    80,    79,    78,    23,     4,    76,     9,     5,
    75,    11,    13,    65,    18,    63,   170,   173,   174,    23,
     4,    62,     9,     5,    39,    11,    13,    65,    18,    25,
   181,    65,   182,    23,     4,   nil,     9,     5,   nil,    11,
    13,     5,    18,    11,    13,    65,    18,   nil,     4,   nil,
     9,   nil,     4,   nil,     9,     5,   nil,    11,    13,   nil,
    18,   nil,   nil,    23,   nil,   nil,     4,     5,     9,    11,
    13,   nil,    18,   nil,   nil,    23,   nil,   nil,     4,     5,
     9,    11,    13,     5,    18,    11,    13,   nil,    18,   nil,
     4,   nil,     9,   nil,     4,   nil,     9,    97,    98,   nil,
   nil,    99,    90,    91,    92,    93,    94,    95,    96,   108,
   109,   nil,   nil,   110,   101,   102,   103,   104,   105,   106,
   107 ]

racc_action_check = [
    24,   158,    24,    24,    64,    64,    64,   108,   158,   158,
     7,     7,    93,    24,    94,    24,    24,    24,    24,    24,
    24,    24,    24,    24,    24,    24,    24,    24,   107,    24,
    24,   106,    96,    53,    95,    51,    91,   117,    90,   117,
   117,    66,    66,   107,   175,    97,   106,    96,    53,    95,
    51,   117,    74,   107,    74,    74,   106,    96,    53,    95,
    51,     0,     0,   176,   175,   176,   176,     0,    67,    67,
    98,     0,    74,     0,     0,   152,     0,    68,    68,     6,
     6,   152,     0,   176,     0,   152,    99,   152,   152,   172,
   152,    17,    17,   119,   119,   172,   152,   101,   152,   172,
   102,   172,   172,    69,   172,   160,   160,   172,   103,    69,
   172,   104,   172,    69,   105,    69,    69,    30,    69,   161,
   161,    40,    40,    30,    69,    77,    69,    30,    61,    30,
    30,    70,    30,     3,     3,   162,   162,    70,    30,    92,
    30,    70,   109,    70,    70,   153,    70,   118,   118,   110,
    59,   153,    70,    57,    70,   153,    56,   153,   153,    38,
   153,    54,    48,    45,    44,    38,   153,    42,   153,    38,
    41,    38,    38,   154,    38,    29,   165,   169,   171,   154,
    38,    25,    38,   154,    22,   154,   154,    71,   154,     2,
   179,    72,   180,    71,   154,   nil,   154,    71,   nil,    71,
    71,    72,    71,    72,    72,    73,    72,   nil,    71,   nil,
    71,   nil,    72,   nil,    72,    73,   nil,    73,    73,   nil,
    73,   nil,   nil,    31,   nil,   nil,    73,    31,    73,    31,
    31,   nil,    31,   nil,   nil,    32,   nil,   nil,    31,    32,
    31,    32,    32,    23,    32,    23,    23,   nil,    23,   nil,
    32,   nil,    32,   nil,    23,   nil,    23,    58,    58,   nil,
   nil,    58,    58,    58,    58,    58,    58,    58,    58,    60,
    60,   nil,   nil,    60,    60,    60,    60,    60,    60,    60,
    60 ]

racc_action_pointer = [
    57,   nil,   189,   129,   nil,   nil,    77,     4,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    83,   nil,   nil,
   nil,   nil,   173,   229,   -12,   181,   nil,   nil,   nil,   149,
   113,   213,   225,   nil,   nil,   nil,   nil,   nil,   155,   nil,
   113,   155,   152,   nil,   149,   148,   nil,   nil,   147,   nil,
   nil,    20,   nil,    18,   146,   nil,   141,   138,   229,   135,
   241,   113,   nil,   nil,     2,   nil,    35,    62,    71,    99,
   127,   183,   187,   201,    48,   nil,   nil,   112,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    23,    21,   124,    -3,    -1,    19,    17,    30,    55,    71,
   nil,    82,    85,    93,    96,    99,    16,    13,    -8,   127,
   134,   nil,   nil,   nil,   nil,   nil,   nil,    33,   139,    85,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    71,   141,   169,   nil,   nil,   nil,   -12,   nil,
    99,   113,   129,   nil,   nil,   163,   nil,   nil,   nil,   164,
   nil,   165,    85,   nil,   nil,    40,    59,   nil,   nil,   170,
   169,   nil,   nil,   nil ]

racc_action_default = [
  -108,   -23,  -108,  -108,  -106,   -25,    -4,    -7,    -2,   -50,
   -34,   -31,    -3,   -36,   -35,   -12,   -32,   -13,  -106,   -33,
   -17,   -18,   -19,  -108,   -21,  -108,    -1,  -104,  -105,  -108,
   -51,    -5,    -6,  -106,  -106,  -106,  -106,  -106,  -108,   -20,
   -14,  -108,  -108,  -106,  -108,  -108,   -27,   -24,  -108,   -28,
   -26,  -108,   -29,  -108,  -108,   -30,  -108,  -108,  -108,  -108,
  -108,  -108,   184,   -49,   -52,  -107,   -56,    -8,    -9,  -108,
  -108,  -108,  -108,  -108,  -108,   -69,   -72,  -108,   -75,   -78,
   -81,   -90,   -99,   -84,   -93,   -96,   -87,   -60,   -61,  -102,
  -108,  -108,  -108,  -108,  -108,  -108,  -108,  -108,  -108,  -108,
  -103,  -108,  -108,  -108,  -108,  -108,  -108,  -108,  -108,  -108,
  -108,   -66,  -106,  -106,  -106,   -10,   -11,  -108,   -15,   -16,
  -106,   -48,  -106,   -22,   -70,   -73,   -76,   -79,   -82,   -91,
  -100,   -85,   -94,   -97,   -88,   -62,   -63,   -67,   -71,   -74,
   -77,   -80,   -83,   -92,  -101,   -86,   -95,   -98,   -89,   -64,
   -65,   -68,   -54,   -55,   -53,  -106,   -40,   -37,  -108,   -47,
   -58,   -59,   -57,   -39,  -106,  -108,   -41,  -106,  -106,  -108,
   -43,  -108,  -108,   -38,   -42,  -108,  -108,  -106,  -106,  -108,
   -44,  -106,   -46,   -45 ]

racc_goto_table = [
    29,    38,   120,     7,    40,    47,     6,    24,    26,     2,
    49,    52,    55,   157,    35,   164,    69,    70,    71,    72,
    73,     3,   165,    64,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    66,    67,    68,   nil,   nil,   nil,    77,
   nil,    74,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   118,   119,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   115,   116,   117,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   152,   153,   154,   nil,   nil,
   nil,   nil,   nil,   177,   178,   159,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   158,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   163,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   172,   nil,   nil,   nil,   160,   161,   162,   nil,   nil,
   169,   nil,   nil,   171,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   179,   180,   176,   nil,   183 ]

racc_goto_check = [
    14,     6,    24,     5,     8,    15,     4,    13,     3,     1,
    16,    17,    18,    21,    22,    23,     6,     6,     6,     6,
     6,     2,    25,    26,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     5,     5,     5,   nil,   nil,   nil,    14,
   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     8,     8,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     5,     5,     5,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     6,     6,     6,   nil,   nil,
   nil,   nil,   nil,    24,    24,     6,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     6,   nil,   nil,   nil,     5,     5,     5,   nil,   nil,
    14,   nil,   nil,    14,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    14,    14,     5,   nil,    14 ]

racc_goto_pointer = [
   nil,     9,    21,     5,     6,     3,   -17,   nil,   -19,   nil,
   nil,   nil,   nil,     6,    -4,   -19,   -14,   -13,   -12,   nil,
   nil,  -104,     1,  -142,   -72,  -136,    -7 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    30,    15,    17,    20,
    21,    22,     1,   nil,   nil,   nil,   nil,    10,    14,    16,
    19,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 "&" => 2,
 ";" => 3,
 "\n" => 4,
 :EOF => 5,
 :AND_AND => 6,
 :OR_OR => 7,
 "|" => 8,
 :BAR_AND => 9,
 :BANG => 10,
 :redirection_list => 11,
 :DO => 12,
 :END => 13,
 :ID => 14,
 :WORD => 15,
 :FOR_COMMAND => 16,
 :WHILE => 17,
 :COND_DO => 18,
 :IF => 19,
 :ELSE => 20,
 :ELSIF => 21,
 :logical_coomand => 22,
 :elif_clause => 23,
 :THEN => 24,
 "(" => 25,
 ")" => 26,
 :RUBYEXP => 27,
 ">" => 28,
 "<" => 29,
 :NUMBER => 30,
 :REDIR_WORD => 31,
 :GREATER_GREATER => 32,
 :GREATER_BAR => 33,
 :LESS_GREATER => 34,
 :LESS_LESS => 35,
 :LESS_LESS_MINUS => 36,
 :LESS_LESS_LESS => 37,
 :LESS_AND => 38,
 :GREATER_AND => 39,
 "-" => 40,
 :AND_GREATER => 41,
 :AND_GREATER_GREATER => 42 }

racc_use_result_var = true

racc_nt_base = 43

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'"&"',
'";"',
'"\n"',
'EOF',
'AND_AND',
'OR_OR',
'"|"',
'BAR_AND',
'BANG',
'redirection_list',
'DO',
'END',
'ID',
'WORD',
'FOR_COMMAND',
'WHILE',
'COND_DO',
'IF',
'ELSE',
'ELSIF',
'logical_coomand',
'elif_clause',
'THEN',
'"("',
'")"',
'RUBYEXP',
'">"',
'"<"',
'NUMBER',
'REDIR_WORD',
'GREATER_GREATER',
'GREATER_BAR',
'LESS_GREATER',
'LESS_LESS',
'LESS_LESS_MINUS',
'LESS_LESS_LESS',
'LESS_AND',
'GREATER_AND',
'"-"',
'AND_GREATER',
'AND_GREATER_GREATER',
'$start',
'inputunit',
'simple_list',
'simple_list_terminator',
'simple_list1',
'logical_command',
'newline_list',
'pipeline_command',
'pipeline',
'command',
'simple_command',
'shell_command',
'simple_command_header',
'simple_command_element_list',
'compound_list',
'simple_command_element',
'redirection',
'group_command',
'ruby_exp_command',
'while_command',
'if_command',
'do',
'@1',
'@2',
'then',
'elsif_clause',
'compound_list1']

Racc_debug_parser = true

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 26
  def _reduce_1( val, _values, result )
		_values.push Node::InputUnit(val[0], val[1])
		yyaccept
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 31
  def _reduce_2( val, _values, result )
		_values.push Node::NOP
  		yyaccept
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 36
  def _reduce_3( val, _values, result )
                _values.push Node::EOF
		yyaccept
   result
  end
.,.,

 # reduce 4 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 43
  def _reduce_5( val, _values, result )
		val[0].last_command_to_async
		result = val[0]
   result
  end
.,.,

 # reduce 6 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 49
  def _reduce_7( val, _values, result )
		result = Node::SeqCommand(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 55
  def _reduce_8( val, _values, result )
		val[0].last_command_to_async
		val[0].add_command(val[2])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 60
  def _reduce_9( val, _values, result )
		val[0].add_command(val[2])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 65
  def _reduce_10( val, _values, result )
		result = Node::ConnectCommandAA(val[0], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 69
  def _reduce_11( val, _values, result )
		result = Node::ConnectCommandOO(val[0], val[3])
   result
  end
.,.,

 # reduce 12 omitted

 # reduce 13 omitted

 # reduce 14 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 97
  def _reduce_15( val, _values, result )
		result = Node::ConnectCommandBAR(val[0], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 101
  def _reduce_16( val, _values, result )
		result = Node::ConnectCommandBAR(val[0], val[3])
   result
  end
.,.,

 # reduce 17 omitted

 # reduce 18 omitted

 # reduce 19 omitted

 # reduce 20 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 112
  def _reduce_21( val, _values, result )
	      result = Node::SimpleCommand(val[0], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 116
  def _reduce_22( val, _values, result )
	      result = Node::SimpleCommand(val[0], val[1], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 121
  def _reduce_23( val, _values, result )
	      result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 125
  def _reduce_24( val, _values, result )
	      result.push val[1]
   result
  end
.,.,

 # reduce 25 omitted

 # reduce 26 omitted

 # reduce 27 omitted

 # reduce 28 omitted

 # reduce 29 omitted

 # reduce 30 omitted

 # reduce 31 omitted

 # reduce 32 omitted

 # reduce 33 omitted

 # reduce 34 omitted

 # reduce 35 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 147
  def _reduce_36( val, _values, result )
@lex.cond_push(true)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 147
  def _reduce_37( val, _values, result )
@lex.cond_pop
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 151
  def _reduce_38( val, _values, result )
	       result = Node::WhileCommand(val[3], val[6])
   result
  end
.,.,

 # reduce 39 omitted

 # reduce 40 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 159
  def _reduce_41( val, _values, result )
		result = Node::IfCommand(val[2], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 163
  def _reduce_42( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[6])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 167
  def _reduce_43( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[5])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 172
  def _reduce_44( val, _values, result )
		result = Node::IfCommand(val[2], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 176
  def _reduce_45( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[6])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 180
  def _reduce_46( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[6])
   result
  end
.,.,

 # reduce 47 omitted

 # reduce 48 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 188
  def _reduce_49( val, _values, result )
	      result = Node::Group(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 192
  def _reduce_50( val, _values, result )
		result = Node::RubyExp(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 197
  def _reduce_51( val, _values, result )
		result = Node::SeqCommand()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 201
  def _reduce_52( val, _values, result )
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 205
  def _reduce_53( val, _values, result )
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 210
  def _reduce_54( val, _values, result )
		val[1].last_command_to_async
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 214
  def _reduce_55( val, _values, result )
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 219
  def _reduce_56( val, _values, result )
	        result = Node::SeqCommand(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 224
  def _reduce_57( val, _values, result )
		val[0].add_command(val[3])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 230
  def _reduce_58( val, _values, result )
		val[0].last_command_to_async
		val[0].add_command(val[3])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 235
  def _reduce_59( val, _values, result )
		val[0].add_command(val[3])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 243
  def _reduce_60( val, _values, result )
	    result = Node::Redirection(1, ">", val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 247
  def _reduce_61( val, _values, result )
	    result = Node::Redirection(0, "<", val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 251
  def _reduce_62( val, _values, result )
	    result = Node::Redirection(val[0], ">", val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 255
  def _reduce_63( val, _values, result )
	    result = Node::Redirection(val[0], "<", val[3])
   result
  end
.,.,

 # reduce 64 omitted

 # reduce 65 omitted

 # reduce 66 omitted

 # reduce 67 omitted

 # reduce 68 omitted

 # reduce 69 omitted

 # reduce 70 omitted

 # reduce 71 omitted

 # reduce 72 omitted

 # reduce 73 omitted

 # reduce 74 omitted

 # reduce 75 omitted

 # reduce 76 omitted

 # reduce 77 omitted

 # reduce 78 omitted

 # reduce 79 omitted

 # reduce 80 omitted

 # reduce 81 omitted

 # reduce 82 omitted

 # reduce 83 omitted

 # reduce 84 omitted

 # reduce 85 omitted

 # reduce 86 omitted

 # reduce 87 omitted

 # reduce 88 omitted

 # reduce 89 omitted

 # reduce 90 omitted

 # reduce 91 omitted

 # reduce 92 omitted

 # reduce 93 omitted

 # reduce 94 omitted

 # reduce 95 omitted

 # reduce 96 omitted

 # reduce 97 omitted

 # reduce 98 omitted

 # reduce 99 omitted

 # reduce 100 omitted

 # reduce 101 omitted

 # reduce 102 omitted

 # reduce 103 omitted

 # reduce 104 omitted

 # reduce 105 omitted

 # reduce 106 omitted

 # reduce 107 omitted

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module Reish
