#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/reish/parser.y".
#

require 'racc/parser'



  require "reish/token"
  require "reish/node"


module Reish

  class Parser < Racc::Parser

module_eval <<'..end lib/reish/parser.y modeval..id972a0e1f03', 'lib/reish/parser.y', 316

  def initialize(lex)
    @yydebug = true

    @lex = lex
  end

  def next_token
    @lex.racc_token
  end
..end lib/reish/parser.y modeval..id972a0e1f03

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 2, 46, :_reduce_1,
 1, 46, :_reduce_2,
 1, 46, :_reduce_3,
 1, 47, :_reduce_none,
 2, 47, :_reduce_5,
 2, 47, :_reduce_none,
 1, 49, :_reduce_7,
 3, 49, :_reduce_8,
 3, 49, :_reduce_9,
 4, 50, :_reduce_10,
 4, 50, :_reduce_11,
 1, 50, :_reduce_none,
 1, 52, :_reduce_none,
 2, 52, :_reduce_none,
 4, 53, :_reduce_15,
 4, 53, :_reduce_16,
 1, 53, :_reduce_none,
 1, 54, :_reduce_none,
 1, 54, :_reduce_none,
 2, 54, :_reduce_none,
 2, 55, :_reduce_21,
 5, 55, :_reduce_22,
 5, 55, :_reduce_23,
 0, 58, :_reduce_24,
 2, 58, :_reduce_25,
 1, 57, :_reduce_none,
 1, 60, :_reduce_none,
 1, 60, :_reduce_none,
 1, 60, :_reduce_none,
 1, 60, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 0, 67, :_reduce_36,
 0, 68, :_reduce_37,
 8, 64, :_reduce_38,
 2, 66, :_reduce_none,
 1, 66, :_reduce_none,
 6, 65, :_reduce_41,
 8, 65, :_reduce_42,
 7, 65, :_reduce_43,
 5, 70, :_reduce_44,
 7, 70, :_reduce_45,
 6, 70, :_reduce_46,
 2, 69, :_reduce_none,
 1, 69, :_reduce_none,
 3, 62, :_reduce_49,
 1, 63, :_reduce_50,
 1, 59, :_reduce_51,
 2, 59, :_reduce_52,
 4, 59, :_reduce_53,
 4, 59, :_reduce_54,
 4, 59, :_reduce_55,
 1, 71, :_reduce_56,
 4, 71, :_reduce_57,
 4, 71, :_reduce_58,
 4, 71, :_reduce_59,
 2, 61, :_reduce_60,
 2, 61, :_reduce_61,
 3, 61, :_reduce_62,
 3, 61, :_reduce_63,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 2, 61, :_reduce_none,
 1, 48, :_reduce_none,
 1, 48, :_reduce_none,
 0, 51, :_reduce_none,
 2, 51, :_reduce_none ]

racc_reduce_n = 108

racc_shift_n = 186

racc_action_table = [
    44,     8,    47,    14,    15,    53,    20,   113,   114,   115,
    37,    38,     7,   123,    12,     7,   152,    12,    57,    59,
    61,    42,    43,    45,    46,    48,    49,    51,    54,    56,
    64,    60,    41,   133,   146,   122,    23,   130,   123,   149,
    34,    35,     8,   128,    14,    15,   129,    20,   135,   148,
   177,    64,   132,     7,   151,    12,    37,    38,   134,   147,
   122,   126,   131,     8,   150,    14,    15,    64,    20,    34,
    35,    64,    34,    35,     7,   125,    12,    23,   136,     8,
   137,    14,    15,     8,    20,    14,    15,    64,    20,   138,
     7,   139,    12,    23,     7,   140,    12,   141,   169,     8,
   142,    14,    15,   143,    20,     6,    10,   167,   168,    64,
     7,    23,    12,    34,    35,    23,   144,     8,    97,    14,
    15,     8,    20,    14,    15,    64,    20,   145,     7,    94,
    12,    23,     7,    99,    12,    37,    38,     8,   124,    14,
    15,    64,    20,    98,    96,    64,   102,    23,     7,   127,
    12,    23,   153,     8,    95,    14,    15,     8,    20,    14,
    15,    64,    20,   101,     7,    64,    12,    23,     7,   100,
    12,    23,    93,     8,    92,    14,    15,     8,    20,    14,
    15,    91,    20,    89,     7,    88,    12,    23,     7,   123,
    12,    34,    35,     8,    86,    14,    15,    75,    20,    23,
    37,    38,    34,    35,     7,     8,    12,    14,    15,    63,
    20,   122,   158,   174,    34,    35,     7,   175,    12,    32,
    33,    34,    35,    27,    29,   111,   112,   176,   159,   103,
   104,   105,   106,   107,   108,   109,   110,    84,    85,    34,
    35,    76,    77,    78,    79,    80,    81,    82,    83,    34,
    35,    62,    26,    24,   183,   184 ]

racc_action_check = [
    25,    23,    25,    23,    23,    25,    23,    65,    65,    65,
    19,    19,    23,   177,    23,    25,   111,    25,    25,    25,
    25,    25,    25,    25,    25,    25,    25,    25,    25,    25,
   173,    25,    25,    83,   109,   177,   173,    82,   178,   110,
   178,   178,   173,    80,   173,   173,    81,   173,    83,   109,
   173,    73,    82,   173,   110,   173,    40,    40,    83,   109,
   178,    78,    82,    73,   110,    73,    73,    72,    73,    67,
    67,    71,    68,    68,    73,    77,    73,    71,    84,    72,
    85,    72,    72,    71,    72,    71,    71,    70,    71,    87,
    72,    90,    72,    70,    71,   103,    71,   104,   160,    70,
   105,    70,    70,   106,    70,     0,     0,   160,   160,    69,
    70,     0,    70,   164,   164,    69,   107,     0,    56,     0,
     0,    69,     0,    69,    69,    31,    69,   108,     0,    54,
     0,    31,    69,    56,    69,   120,   120,    31,    76,    31,
    31,    39,    31,    56,    54,   154,    60,    39,    31,    79,
    31,   154,   112,    39,    54,    39,    39,   154,    39,   154,
   154,   156,   154,    59,    39,   155,    39,   156,   154,    57,
   154,   155,    51,   156,    49,   156,   156,   155,   156,   155,
   155,    48,   155,    46,   156,    45,   156,    33,   155,    74,
   155,    74,    74,    33,    43,    33,    33,    41,    33,    32,
   119,   119,    11,    11,    33,    32,    33,    32,    32,    30,
    32,    74,   118,   170,   118,   118,    32,   171,    32,     9,
     9,   163,   163,     5,     5,    61,    61,   172,   118,    61,
    61,    61,    61,    61,    61,    61,    61,    42,    42,   162,
   162,    42,    42,    42,    42,    42,    42,    42,    42,    66,
    66,    26,     4,     2,   181,   182 ]

racc_action_pointer = [
   101,   nil,   242,   nil,   252,   219,   nil,   nil,   nil,   217,
   nil,   196,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,
   nil,   nil,   nil,   -15,   nil,   -12,   251,   nil,   nil,   nil,
   181,   121,   189,   177,   nil,   nil,   nil,   nil,   nil,   137,
    48,   180,   207,   177,   nil,   168,   166,   nil,   164,   157,
   nil,   155,   nil,   nil,   112,   nil,   101,   152,   nil,   146,
   129,   195,   nil,   nil,   nil,     5,   243,    63,    66,   105,
    83,    67,    63,    47,   185,   nil,   121,    58,    44,   132,
    26,    29,    20,    16,    61,    63,   nil,    76,   nil,   nil,
    76,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    78,    80,    83,    86,    99,   110,    17,
    22,    -1,   135,   nil,   nil,   nil,   nil,   nil,   208,   192,
   127,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   141,   161,   157,   nil,   nil,   nil,
    85,   nil,   233,   215,   107,   nil,   nil,   nil,   nil,   nil,
   200,   204,   214,    26,   nil,   nil,   nil,     9,    34,   nil,
   nil,   232,   230,   nil,   nil,   nil ]

racc_action_default = [
  -108,   -18,   -19,   -24,  -108,  -108,    -2,  -106,   -26,    -4,
    -3,    -7,   -50,   -34,   -31,   -36,   -35,   -12,   -32,   -13,
  -106,   -33,   -17,  -108,   -20,   -21,  -108,  -104,    -1,  -105,
  -108,   -51,    -5,    -6,  -106,  -106,  -106,  -106,  -106,  -108,
   -14,  -108,  -108,  -108,  -106,  -108,  -108,  -106,  -108,  -108,
   -25,  -108,   -28,   -27,  -108,   -29,  -108,  -108,   -30,  -108,
  -108,  -108,   186,   -49,  -107,   -52,   -56,    -8,    -9,  -108,
  -108,  -108,  -108,  -108,  -108,  -103,  -108,  -108,  -108,  -108,
  -108,  -108,  -108,  -108,  -108,  -108,   -66,  -108,   -69,   -72,
  -108,   -75,   -78,   -81,   -90,   -99,   -84,   -93,   -96,   -87,
   -60,   -61,  -102,  -108,  -108,  -108,  -108,  -108,  -108,  -108,
  -108,  -108,  -108,  -106,  -106,  -106,   -10,   -11,  -108,   -15,
   -16,  -106,   -48,  -106,   -68,   -71,   -74,   -77,   -80,   -83,
   -92,  -101,   -86,   -95,   -98,   -89,   -64,   -65,   -22,   -23,
   -67,   -70,   -73,   -76,   -79,   -82,   -91,  -100,   -85,   -94,
   -97,   -88,   -62,   -63,   -54,   -55,   -53,   -37,  -106,   -40,
  -108,   -47,   -58,   -59,   -57,  -106,   -39,  -106,  -106,   -41,
  -108,  -108,  -108,  -108,   -43,   -38,   -42,  -108,  -108,  -106,
  -106,  -108,   -44,  -106,   -46,   -45 ]

racc_goto_table = [
    30,    39,   121,    40,    50,     9,    25,    28,     4,    52,
    11,    55,    58,   157,    36,    69,    70,    71,    72,    73,
   165,     5,   170,    65,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    87,   nil,   nil,
    90,    66,    67,    68,   nil,   nil,   nil,   nil,   nil,    74,
   nil,   nil,   119,   120,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   116,
   117,   118,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   154,   155,   156,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   161,   179,   180,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   160,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   166,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   173,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   171,   nil,
   172,   nil,   nil,   nil,   162,   163,   164,   nil,   nil,   nil,
   nil,   nil,   181,   182,   nil,   nil,   185,   nil,   nil,   nil,
   nil,   nil,   nil,   178 ]

racc_goto_check = [
    14,     6,    24,     8,    15,     4,    13,     3,     1,    16,
     5,    17,    18,    21,    22,     6,     6,     6,     6,     6,
    23,     2,    25,    26,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil,   nil,
    14,     5,     5,     5,   nil,   nil,   nil,   nil,   nil,     5,
   nil,   nil,     8,     8,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,
     5,     5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     6,     6,     6,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     6,    24,    24,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    14,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil,
    14,   nil,   nil,   nil,     5,     5,     5,   nil,   nil,   nil,
   nil,   nil,    14,    14,   nil,   nil,    14,   nil,   nil,   nil,
   nil,   nil,   nil,     5 ]

racc_goto_pointer = [
   nil,     8,    21,     2,     5,    10,   -19,   nil,   -20,   nil,
   nil,   nil,   nil,     3,    -7,   -21,   -16,   -14,   -13,   nil,
   nil,  -105,    -1,  -137,   -72,  -138,    -8 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    31,    17,    19,    22,
     1,     2,     3,   nil,   nil,   nil,   nil,    13,    16,    18,
    21,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 "&" => 2,
 ";" => 3,
 "\n" => 4,
 :EOF => 5,
 :AND_AND => 6,
 :OR_OR => 7,
 "|" => 8,
 :BAR_AND => 9,
 :BANG => 10,
 :redirection_list => 11,
 :DO => 12,
 :END => 13,
 "{" => 14,
 "}" => 15,
 :ID => 16,
 :WORD => 17,
 :FOR_COMMAND => 18,
 :WHILE => 19,
 :COND_DO => 20,
 :IF => 21,
 :ELSE => 22,
 :ELSIF => 23,
 :logical_coomand => 24,
 :elif_clause => 25,
 :THEN => 26,
 "(" => 27,
 ")" => 28,
 :RUBYEXP => 29,
 ">" => 30,
 "<" => 31,
 :NUMBER => 32,
 :REDIR_WORD => 33,
 :GREATER_GREATER => 34,
 :GREATER_BAR => 35,
 :LESS_GREATER => 36,
 :LESS_LESS => 37,
 :LESS_LESS_MINUS => 38,
 :LESS_LESS_LESS => 39,
 :LESS_AND => 40,
 :GREATER_AND => 41,
 "-" => 42,
 :AND_GREATER => 43,
 :AND_GREATER_GREATER => 44 }

racc_use_result_var = true

racc_nt_base = 45

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'"&"',
'";"',
'"\n"',
'EOF',
'AND_AND',
'OR_OR',
'"|"',
'BAR_AND',
'BANG',
'redirection_list',
'DO',
'END',
'"{"',
'"}"',
'ID',
'WORD',
'FOR_COMMAND',
'WHILE',
'COND_DO',
'IF',
'ELSE',
'ELSIF',
'logical_coomand',
'elif_clause',
'THEN',
'"("',
'")"',
'RUBYEXP',
'">"',
'"<"',
'NUMBER',
'REDIR_WORD',
'GREATER_GREATER',
'GREATER_BAR',
'LESS_GREATER',
'LESS_LESS',
'LESS_LESS_MINUS',
'LESS_LESS_LESS',
'LESS_AND',
'GREATER_AND',
'"-"',
'AND_GREATER',
'AND_GREATER_GREATER',
'$start',
'inputunit',
'simple_list',
'simple_list_terminator',
'simple_list1',
'logical_command',
'newline_list',
'pipeline_command',
'pipeline',
'command',
'simple_command',
'shell_command',
'simple_command_header',
'simple_command_element_list',
'compound_list',
'simple_command_element',
'redirection',
'group_command',
'ruby_exp_command',
'while_command',
'if_command',
'do',
'@1',
'@2',
'then',
'elsif_clause',
'compound_list1']

Racc_debug_parser = true

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 26
  def _reduce_1( val, _values, result )
		_values.push Node::InputUnit(val[0], val[1])
	        yyaccept
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 31
  def _reduce_2( val, _values, result )
		_values.push Node::NOP
  		yyaccept
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 36
  def _reduce_3( val, _values, result )
                _values.push Node::EOF
		yyaccept
   result
  end
.,.,

 # reduce 4 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 43
  def _reduce_5( val, _values, result )
		val[0].last_command_to_async
		result = val[0]
   result
  end
.,.,

 # reduce 6 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 50
  def _reduce_7( val, _values, result )
		result = Node::SeqCommand(val[0])
#	        result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 56
  def _reduce_8( val, _values, result )
		val[0].last_command_to_async
		val[0].add_command(val[2])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 61
  def _reduce_9( val, _values, result )
		val[0].add_command(val[2])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 66
  def _reduce_10( val, _values, result )
		result = Node::ConnectCommandAA(val[0], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 70
  def _reduce_11( val, _values, result )
		result = Node::ConnectCommandOO(val[0], val[3])
   result
  end
.,.,

 # reduce 12 omitted

 # reduce 13 omitted

 # reduce 14 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 98
  def _reduce_15( val, _values, result )
		result = Node::ConnectCommandBAR(val[0], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 102
  def _reduce_16( val, _values, result )
		result = Node::ConnectCommandBAR(val[0], val[3])
   result
  end
.,.,

 # reduce 17 omitted

 # reduce 18 omitted

 # reduce 19 omitted

 # reduce 20 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 113
  def _reduce_21( val, _values, result )
	      result = Node::SimpleCommand(val[0], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 117
  def _reduce_22( val, _values, result )
	      result = Node::SimpleCommand(val[0], val[1], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 121
  def _reduce_23( val, _values, result )
	      result = Node::SimpleCommand(val[0], val[1], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 126
  def _reduce_24( val, _values, result )
	       result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 130
  def _reduce_25( val, _values, result )
	       result.push val[1]
   result
  end
.,.,

 # reduce 26 omitted

 # reduce 27 omitted

 # reduce 28 omitted

 # reduce 29 omitted

 # reduce 30 omitted

 # reduce 31 omitted

 # reduce 32 omitted

 # reduce 33 omitted

 # reduce 34 omitted

 # reduce 35 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 152
  def _reduce_36( val, _values, result )
@lex.cond_push(true)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 152
  def _reduce_37( val, _values, result )
@lex.cond_pop
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 156
  def _reduce_38( val, _values, result )
	       result = Node::WhileCommand(val[3], val[6])
   result
  end
.,.,

 # reduce 39 omitted

 # reduce 40 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 164
  def _reduce_41( val, _values, result )
		result = Node::IfCommand(val[2], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 168
  def _reduce_42( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[6])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 172
  def _reduce_43( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[5])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 177
  def _reduce_44( val, _values, result )
		result = Node::IfCommand(val[2], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 181
  def _reduce_45( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[6])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 185
  def _reduce_46( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[6])
   result
  end
.,.,

 # reduce 47 omitted

 # reduce 48 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 193
  def _reduce_49( val, _values, result )
	      result = Node::Group(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 197
  def _reduce_50( val, _values, result )
		result = Node::RubyExp(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 202
  def _reduce_51( val, _values, result )
		result = Node::SeqCommand()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 206
  def _reduce_52( val, _values, result )
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 210
  def _reduce_53( val, _values, result )
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 215
  def _reduce_54( val, _values, result )
		val[1].last_command_to_async
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 219
  def _reduce_55( val, _values, result )
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 224
  def _reduce_56( val, _values, result )
	        result = Node::SeqCommand(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 229
  def _reduce_57( val, _values, result )
		val[0].add_command(val[3])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 235
  def _reduce_58( val, _values, result )
		val[0].last_command_to_async
		val[0].add_command(val[3])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 240
  def _reduce_59( val, _values, result )
		val[0].add_command(val[3])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 248
  def _reduce_60( val, _values, result )
	    result = Node::Redirection(1, ">", val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 252
  def _reduce_61( val, _values, result )
	    result = Node::Redirection(0, "<", val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 256
  def _reduce_62( val, _values, result )
	    result = Node::Redirection(val[0], ">", val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 260
  def _reduce_63( val, _values, result )
	    result = Node::Redirection(val[0], "<", val[3])
   result
  end
.,.,

 # reduce 64 omitted

 # reduce 65 omitted

 # reduce 66 omitted

 # reduce 67 omitted

 # reduce 68 omitted

 # reduce 69 omitted

 # reduce 70 omitted

 # reduce 71 omitted

 # reduce 72 omitted

 # reduce 73 omitted

 # reduce 74 omitted

 # reduce 75 omitted

 # reduce 76 omitted

 # reduce 77 omitted

 # reduce 78 omitted

 # reduce 79 omitted

 # reduce 80 omitted

 # reduce 81 omitted

 # reduce 82 omitted

 # reduce 83 omitted

 # reduce 84 omitted

 # reduce 85 omitted

 # reduce 86 omitted

 # reduce 87 omitted

 # reduce 88 omitted

 # reduce 89 omitted

 # reduce 90 omitted

 # reduce 91 omitted

 # reduce 92 omitted

 # reduce 93 omitted

 # reduce 94 omitted

 # reduce 95 omitted

 # reduce 96 omitted

 # reduce 97 omitted

 # reduce 98 omitted

 # reduce 99 omitted

 # reduce 100 omitted

 # reduce 101 omitted

 # reduce 102 omitted

 # reduce 103 omitted

 # reduce 104 omitted

 # reduce 105 omitted

 # reduce 106 omitted

 # reduce 107 omitted

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module Reish
