#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/reish/parser.y".
#

require 'racc/parser'



  require "reish/token"
  require "reish/node"


module Reish

  class Parser < Racc::Parser

module_eval <<'..end lib/reish/parser.y modeval..id1cc8f2a80a', 'lib/reish/parser.y', 323

  def initialize(lex)
    @yydebug = true

    @lex = lex
  end

  def next_token
    @lex.racc_token
  end
..end lib/reish/parser.y modeval..id1cc8f2a80a

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 2, 46, :_reduce_1,
 1, 46, :_reduce_2,
 1, 46, :_reduce_3,
 1, 47, :_reduce_none,
 2, 47, :_reduce_5,
 2, 47, :_reduce_none,
 1, 49, :_reduce_7,
 3, 49, :_reduce_8,
 3, 49, :_reduce_9,
 4, 50, :_reduce_10,
 4, 50, :_reduce_11,
 1, 50, :_reduce_none,
 1, 52, :_reduce_none,
 2, 52, :_reduce_none,
 4, 53, :_reduce_15,
 4, 53, :_reduce_16,
 1, 53, :_reduce_17,
 1, 54, :_reduce_none,
 1, 54, :_reduce_none,
 2, 54, :_reduce_none,
 2, 55, :_reduce_21,
 5, 55, :_reduce_22,
 5, 55, :_reduce_23,
 0, 58, :_reduce_24,
 2, 58, :_reduce_25,
 1, 57, :_reduce_none,
 1, 60, :_reduce_none,
 1, 60, :_reduce_none,
 1, 60, :_reduce_none,
 1, 60, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 0, 67, :_reduce_36,
 0, 68, :_reduce_37,
 8, 65, :_reduce_38,
 2, 66, :_reduce_none,
 2, 66, :_reduce_none,
 1, 66, :_reduce_none,
 6, 64, :_reduce_42,
 8, 64, :_reduce_43,
 7, 64, :_reduce_44,
 5, 70, :_reduce_45,
 7, 70, :_reduce_46,
 6, 70, :_reduce_47,
 2, 69, :_reduce_none,
 1, 69, :_reduce_none,
 1, 69, :_reduce_none,
 3, 62, :_reduce_51,
 1, 63, :_reduce_52,
 1, 59, :_reduce_53,
 2, 59, :_reduce_54,
 4, 59, :_reduce_55,
 4, 59, :_reduce_56,
 4, 59, :_reduce_57,
 1, 71, :_reduce_58,
 4, 71, :_reduce_59,
 4, 71, :_reduce_60,
 4, 71, :_reduce_61,
 2, 61, :_reduce_62,
 2, 61, :_reduce_63,
 3, 61, :_reduce_64,
 3, 61, :_reduce_65,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 3, 61, :_reduce_none,
 3, 61, :_reduce_none,
 2, 61, :_reduce_none,
 2, 61, :_reduce_none,
 1, 48, :_reduce_none,
 1, 48, :_reduce_none,
 0, 51, :_reduce_none,
 2, 51, :_reduce_none ]

racc_reduce_n = 110

racc_shift_n = 189

racc_action_table = [
    44,     8,    47,    14,    15,    53,    20,   113,   114,   115,
   121,   124,     7,   139,    12,     7,   127,    12,    57,    59,
    61,    42,    43,    45,    46,    48,    49,    51,    54,    56,
   147,    60,    41,   123,    64,    37,    38,   128,   150,   129,
    23,    34,    35,    34,    35,   149,     8,   130,    14,    15,
    64,    20,   125,   152,    64,   148,    23,     7,    63,    12,
    23,   137,     8,   151,    14,    15,     8,    20,    14,    15,
   180,    20,    64,     7,   138,    12,    64,     7,    23,    12,
   126,    97,    23,   140,     8,   141,    14,    15,     8,    20,
    14,    15,   142,    20,   143,     7,    99,    12,    64,     7,
   144,    12,     6,    10,    23,   145,    98,   146,    23,    62,
     8,   131,    14,    15,     8,    20,    14,    15,    64,    20,
    75,     7,    94,    12,    23,     7,   133,    12,    34,    35,
     8,   153,    14,    15,    64,    20,   132,    96,    64,   154,
    23,     7,    86,    12,    32,    33,     8,    95,    14,    15,
     8,    20,    14,    15,    64,    20,    88,     7,    64,    12,
    92,     7,   102,    12,    23,   134,     8,   101,    14,    15,
     8,    20,    14,    15,   100,    20,    89,     7,    91,    12,
   136,     7,   177,    12,   121,   124,   178,    34,    35,   179,
   135,   121,   124,    23,    34,    35,    34,    35,    93,     8,
    23,    14,    15,    26,    20,    24,     8,   123,    14,    15,
     7,    20,    12,   186,   123,    34,    35,     7,   172,    12,
   159,   160,   187,    34,    35,    84,    85,   170,   171,    76,
    77,    78,    79,    80,    81,    82,    83,   161,   111,   112,
    34,    35,   103,   104,   105,   106,   107,   108,   109,   110,
    37,    38,    27,    29,    34,    35 ]

racc_action_check = [
    25,    23,    25,    23,    23,    25,    23,    65,    65,    65,
   180,   180,    23,    87,    23,    25,    78,    25,    25,    25,
    25,    25,    25,    25,    25,    25,    25,    25,    25,    25,
   109,    25,    25,   180,    69,    19,    19,    79,   110,    80,
    69,    11,    11,    67,    67,   109,    69,    81,    69,    69,
   176,    69,    76,   110,   157,   109,   176,    69,    30,    69,
   157,    84,   176,   110,   176,   176,   157,   176,   157,   157,
   176,   157,   156,   176,    85,   176,   155,   157,   156,   157,
    77,    56,   155,    90,   156,   103,   156,   156,   155,   156,
   155,   155,   104,   155,   105,   156,    56,   156,    70,   155,
   106,   155,     0,     0,    70,   107,    56,   108,     0,    26,
    70,    82,    70,    70,     0,    70,     0,     0,    31,     0,
    41,    70,    54,    70,    31,     0,    82,     0,    68,    68,
    31,   111,    31,    31,    39,    31,    82,    54,    73,   112,
    39,    31,    43,    31,     9,     9,    39,    54,    39,    39,
    73,    39,    73,    73,    72,    73,    45,    39,    71,    39,
    49,    73,    60,    73,    71,    83,    72,    59,    72,    72,
    71,    72,    71,    71,    57,    71,    46,    72,    48,    72,
    83,    71,   173,    71,   181,   181,   174,   181,   181,   175,
    83,    74,    74,    32,    74,    74,   164,   164,    51,    32,
    33,    32,    32,     4,    32,     2,    33,   181,    33,    33,
    32,    33,    32,   184,    74,   165,   165,    33,   162,    33,
   118,   118,   185,   118,   118,    42,    42,   162,   162,    42,
    42,    42,    42,    42,    42,    42,    42,   118,    61,    61,
   166,   166,    61,    61,    61,    61,    61,    61,    61,    61,
    40,    40,     5,     5,    66,    66 ]

racc_action_pointer = [
    98,   nil,   194,   nil,   203,   248,   nil,   nil,   nil,   142,
   nil,    35,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    27,
   nil,   nil,   nil,   -15,   nil,   -12,   109,   nil,   nil,   nil,
    30,   114,   183,   190,   nil,   nil,   nil,   nil,   nil,   130,
   242,   103,   195,   125,   nil,   139,   159,   nil,   161,   143,
   nil,   181,   nil,   nil,   105,   nil,    64,   157,   nil,   150,
   145,   208,   nil,   nil,   nil,     5,   248,    37,   122,    30,
    94,   154,   150,   134,   188,   nil,    35,    63,    -1,    20,
    22,    30,    94,   148,    44,    57,   nil,     0,   nil,   nil,
    68,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    68,    75,    77,    83,    88,    90,    13,
    21,   114,   122,   nil,   nil,   nil,   nil,   nil,   217,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    72,    68,    50,   nil,   nil,
   nil,   nil,   205,   nil,   190,   209,   234,   nil,   nil,   nil,
   nil,   nil,   nil,   169,   173,   176,    46,   nil,   nil,   nil,
     7,   181,   nil,   nil,   191,   197,   nil,   nil,   nil ]

racc_action_default = [
  -110,   -18,   -19,   -24,  -110,  -110,    -2,  -108,   -26,    -4,
    -3,    -7,   -52,   -34,   -31,   -36,   -35,   -12,   -32,   -13,
  -108,   -33,   -17,  -110,   -20,   -21,  -110,  -106,    -1,  -107,
  -110,   -53,    -5,    -6,  -108,  -108,  -108,  -108,  -108,  -110,
   -14,  -110,  -110,  -110,  -108,  -110,  -110,  -108,  -110,  -110,
   -25,  -110,   -28,   -27,  -110,   -29,  -110,  -110,   -30,  -110,
  -110,  -110,   189,   -51,  -109,   -54,   -58,    -8,    -9,  -110,
  -110,  -110,  -110,  -110,  -110,  -105,  -110,  -110,  -110,  -110,
  -110,  -110,  -110,  -110,  -110,  -110,   -68,  -110,   -71,   -74,
  -110,   -77,   -80,   -83,   -92,  -101,   -86,   -95,   -98,   -89,
   -62,   -63,  -104,  -110,  -110,  -110,  -110,  -110,  -110,  -110,
  -110,  -110,  -110,  -108,  -108,  -108,   -10,   -11,  -110,   -15,
   -16,   -49,  -108,   -50,  -108,   -70,   -73,   -76,   -79,   -82,
   -85,   -94,  -103,   -88,   -97,  -100,   -91,   -66,   -67,   -22,
   -23,   -69,   -72,   -75,   -78,   -81,   -84,   -93,  -102,   -87,
   -96,   -99,   -90,   -64,   -65,   -56,   -57,   -55,   -37,  -108,
  -108,   -41,  -110,   -48,   -60,   -61,   -59,  -108,   -40,   -39,
  -108,  -108,   -42,  -110,  -110,  -110,  -110,   -44,   -38,   -43,
  -110,  -110,  -108,  -108,  -110,   -45,  -108,   -47,   -46 ]

racc_goto_table = [
    30,    39,    11,   122,   119,   120,    50,    40,     9,    25,
    28,     4,    52,    55,    58,    69,    70,    71,    72,    73,
   158,    36,   167,     5,   173,    65,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    66,    67,    68,   nil,    87,   nil,   nil,
    90,    74,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   116,   117,   118,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   155,   156,   157,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   163,   nil,   nil,   nil,   182,
   183,   nil,   nil,   nil,   nil,   162,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   168,   169,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   176,   nil,   nil,   nil,   nil,   164,   165,   166,
   174,   nil,   nil,   175,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   184,   185,   nil,   181,   188 ]

racc_goto_check = [
    14,     6,     5,    24,     9,     9,    15,     8,     4,    13,
     3,     1,    16,    17,    18,     6,     6,     6,     6,     6,
    21,    22,    23,     2,    25,    26,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     5,     5,     5,   nil,    14,   nil,   nil,
    14,     5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     5,     5,     5,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     6,     6,     6,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     6,   nil,   nil,   nil,    24,
    24,   nil,   nil,   nil,   nil,    14,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     6,     6,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     6,   nil,   nil,   nil,   nil,     5,     5,     5,
    14,   nil,   nil,    14,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    14,    14,   nil,     5,    14 ]

racc_goto_pointer = [
   nil,    11,    23,     5,     8,     2,   -19,   nil,   -16,   -68,
   nil,   nil,   nil,     6,    -7,   -19,   -13,   -12,   -11,   nil,
   nil,   -98,     6,  -136,   -71,  -138,    -6 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    31,    17,    19,    22,
     1,     2,     3,   nil,   nil,   nil,   nil,    13,    16,    18,
    21,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 "&" => 2,
 ";" => 3,
 "\n" => 4,
 :EOF => 5,
 :AND_AND => 6,
 :OR_OR => 7,
 "|" => 8,
 :BAR_AND => 9,
 :BANG => 10,
 :redirection_list => 11,
 :DO => 12,
 :END => 13,
 "{" => 14,
 "}" => 15,
 :ID => 16,
 :WORD => 17,
 :FOR_COMMAND => 18,
 :WHILE => 19,
 :COND_DO => 20,
 :IF => 21,
 :ELSE => 22,
 :ELSIF => 23,
 :logical_coomand => 24,
 :elif_clause => 25,
 :THEN => 26,
 "(" => 27,
 ")" => 28,
 :RUBYEXP => 29,
 ">" => 30,
 "<" => 31,
 :NUMBER => 32,
 :REDIR_WORD => 33,
 :GREATER_GREATER => 34,
 :GREATER_BAR => 35,
 :LESS_GREATER => 36,
 :LESS_LESS => 37,
 :LESS_LESS_MINUS => 38,
 :LESS_LESS_LESS => 39,
 :LESS_AND => 40,
 :GREATER_AND => 41,
 "-" => 42,
 :AND_GREATER => 43,
 :AND_GREATER_GREATER => 44 }

racc_use_result_var = true

racc_nt_base = 45

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'"&"',
'";"',
'"\n"',
'EOF',
'AND_AND',
'OR_OR',
'"|"',
'BAR_AND',
'BANG',
'redirection_list',
'DO',
'END',
'"{"',
'"}"',
'ID',
'WORD',
'FOR_COMMAND',
'WHILE',
'COND_DO',
'IF',
'ELSE',
'ELSIF',
'logical_coomand',
'elif_clause',
'THEN',
'"("',
'")"',
'RUBYEXP',
'">"',
'"<"',
'NUMBER',
'REDIR_WORD',
'GREATER_GREATER',
'GREATER_BAR',
'LESS_GREATER',
'LESS_LESS',
'LESS_LESS_MINUS',
'LESS_LESS_LESS',
'LESS_AND',
'GREATER_AND',
'"-"',
'AND_GREATER',
'AND_GREATER_GREATER',
'$start',
'inputunit',
'simple_list',
'simple_list_terminator',
'simple_list1',
'logical_command',
'newline_list',
'pipeline_command',
'pipeline',
'command',
'simple_command',
'shell_command',
'simple_command_header',
'simple_command_element_list',
'compound_list',
'simple_command_element',
'redirection',
'group_command',
'ruby_exp_command',
'if_command',
'while_command',
'do',
'@1',
'@2',
'then',
'elsif_clause',
'compound_list1']

Racc_debug_parser = true

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 26
  def _reduce_1( val, _values, result )
		_values.push Node::InputUnit(val[0], val[1])
	        yyaccept
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 31
  def _reduce_2( val, _values, result )
		_values.push Node::NOP
  		yyaccept
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 36
  def _reduce_3( val, _values, result )
                _values.push Node::EOF
		yyaccept
   result
  end
.,.,

 # reduce 4 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 43
  def _reduce_5( val, _values, result )
		val[0].last_command_to_async
		result = val[0]
   result
  end
.,.,

 # reduce 6 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 50
  def _reduce_7( val, _values, result )
		result = Node::SeqCommand(val[0])
#	        result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 56
  def _reduce_8( val, _values, result )
		val[0].last_command_to_async
		val[0].add_command(val[2])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 61
  def _reduce_9( val, _values, result )
		val[0].add_command(val[2])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 66
  def _reduce_10( val, _values, result )
		result = Node::ConnectCommandAA(val[0], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 70
  def _reduce_11( val, _values, result )
		result = Node::ConnectCommandOO(val[0], val[3])
   result
  end
.,.,

 # reduce 12 omitted

 # reduce 13 omitted

 # reduce 14 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 99
  def _reduce_15( val, _values, result )
	       result = val[0]
  	       result.pipe_command(:BAR, val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 104
  def _reduce_16( val, _values, result )
	       result = val[0]
  	       result.pipe_command(:BAR_AND, val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 108
  def _reduce_17( val, _values, result )
		result = Node::PipelineCommand(val[0])
   result
  end
.,.,

 # reduce 18 omitted

 # reduce 19 omitted

 # reduce 20 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 118
  def _reduce_21( val, _values, result )
	      result = Node::SimpleCommand(val[0], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 122
  def _reduce_22( val, _values, result )
	      result = Node::SimpleCommand(val[0], val[1], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 126
  def _reduce_23( val, _values, result )
	      result = Node::SimpleCommand(val[0], val[1], val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 131
  def _reduce_24( val, _values, result )
	       result = []
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 135
  def _reduce_25( val, _values, result )
	       result.push val[1]
   result
  end
.,.,

 # reduce 26 omitted

 # reduce 27 omitted

 # reduce 28 omitted

 # reduce 29 omitted

 # reduce 30 omitted

 # reduce 31 omitted

 # reduce 32 omitted

 # reduce 33 omitted

 # reduce 34 omitted

 # reduce 35 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 157
  def _reduce_36( val, _values, result )
@lex.cond_push(true)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 157
  def _reduce_37( val, _values, result )
@lex.cond_pop
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 161
  def _reduce_38( val, _values, result )
	       result = Node::WhileCommand(val[3], val[6])
   result
  end
.,.,

 # reduce 39 omitted

 # reduce 40 omitted

 # reduce 41 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 170
  def _reduce_42( val, _values, result )
		result = Node::IfCommand(val[2], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 174
  def _reduce_43( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[6])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 178
  def _reduce_44( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[5])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 183
  def _reduce_45( val, _values, result )
		result = Node::IfCommand(val[2], val[4])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 187
  def _reduce_46( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[6])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 191
  def _reduce_47( val, _values, result )
		result = Node::IfCommand(val[2], val[4], val[6])
   result
  end
.,.,

 # reduce 48 omitted

 # reduce 49 omitted

 # reduce 50 omitted

module_eval <<'.,.,', 'lib/reish/parser.y', 200
  def _reduce_51( val, _values, result )
	      result = Node::Group(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 204
  def _reduce_52( val, _values, result )
		result = Node::RubyExp(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 209
  def _reduce_53( val, _values, result )
		result = Node::SeqCommand()
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 213
  def _reduce_54( val, _values, result )
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 217
  def _reduce_55( val, _values, result )
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 222
  def _reduce_56( val, _values, result )
		val[1].last_command_to_async
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 226
  def _reduce_57( val, _values, result )
		result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 231
  def _reduce_58( val, _values, result )
	        result = Node::SeqCommand(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 236
  def _reduce_59( val, _values, result )
		val[0].add_command(val[3])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 242
  def _reduce_60( val, _values, result )
		val[0].last_command_to_async
		val[0].add_command(val[3])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 247
  def _reduce_61( val, _values, result )
		val[0].add_command(val[3])
		result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 255
  def _reduce_62( val, _values, result )
	    result = Node::Redirection(1, ">", val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 259
  def _reduce_63( val, _values, result )
	    result = Node::Redirection(0, "<", val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 263
  def _reduce_64( val, _values, result )
	    result = Node::Redirection(val[0], ">", val[3])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/reish/parser.y', 267
  def _reduce_65( val, _values, result )
	    result = Node::Redirection(val[0], "<", val[3])
   result
  end
.,.,

 # reduce 66 omitted

 # reduce 67 omitted

 # reduce 68 omitted

 # reduce 69 omitted

 # reduce 70 omitted

 # reduce 71 omitted

 # reduce 72 omitted

 # reduce 73 omitted

 # reduce 74 omitted

 # reduce 75 omitted

 # reduce 76 omitted

 # reduce 77 omitted

 # reduce 78 omitted

 # reduce 79 omitted

 # reduce 80 omitted

 # reduce 81 omitted

 # reduce 82 omitted

 # reduce 83 omitted

 # reduce 84 omitted

 # reduce 85 omitted

 # reduce 86 omitted

 # reduce 87 omitted

 # reduce 88 omitted

 # reduce 89 omitted

 # reduce 90 omitted

 # reduce 91 omitted

 # reduce 92 omitted

 # reduce 93 omitted

 # reduce 94 omitted

 # reduce 95 omitted

 # reduce 96 omitted

 # reduce 97 omitted

 # reduce 98 omitted

 # reduce 99 omitted

 # reduce 100 omitted

 # reduce 101 omitted

 # reduce 102 omitted

 # reduce 103 omitted

 # reduce 104 omitted

 # reduce 105 omitted

 # reduce 106 omitted

 # reduce 107 omitted

 # reduce 108 omitted

 # reduce 109 omitted

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module Reish
